import { useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import { Button } from "~/components/design-system/Button";
import { Input } from "~/components/design-system/Input";

const Home: NextPage = () => {
  const [url, setUrl] = useState("");
  const [message, setMessage] = useState("");
  const crawlMutation = api.crawler.createIndexes.useMutation();
  const sendMessageMutation = api.chat.sendMessage.useMutation();

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className="container mt-12 flex flex-col items-center justify-center gap-4 px-4 py-8">
          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            Source Crawler
          </h1>

          {/* <Input
            onChange={(e) => {
              setUrl(e.target.value);
            }}
            value={url}
          />
          <Button
            onClick={() => {
              void crawlMutation.mutate({ url });
            }}
          >
            Crawl
          </Button> */}
          <Input value={message} onChange={(e) => setMessage(e.target.value)} />
          <Button
            onClick={() => {
              sendMessageMutation.mutate({ message });
            }}
          >
            message
          </Button>
          {sendMessageMutation.isLoading ? (
            <p>loading...</p>
          ) : (
            <>
              <p>{sendMessageMutation.data?.text}</p>
              <p>
                sources: {JSON.stringify(sendMessageMutation.data?.documents)}
              </p>
            </>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
